### ISSUE TITLE
[imports/civilian_2] Handling issues with the Toyota Chaser

### ISSUE THREAD

**Issue by ItsBeckyy** [InZidiuZ/legacy-assets-issue-tracker#336] opened 2021-03-17 22:52 UTC
**Reporter:**
ItsBeckyy#1185

**Summary:**
I bought the Toyota Chaser today in the import ship and had no idea you can test out the cars but that car has no traction whatsoever and I get its a drift car but its undriveable in its current state even with a tuner chip its still undriveable.

## Additional Information

**Screenshots:**
N/A 

**Notes:**
I was told I should have asked around for people that own the car but I think I'm the only person in the city that owns one as I have seen no one with one to ask.

**Comment by joevapes3** [comment] 2021-03-24 18:31
Yah this is not a bug with the vehicle and in turn the car is setup for drifting. If you understand driving a drift car in GTA, it is more than capable of being driven. There are a few different people that own the car within the city and are able to drive it just fine while drifting. Best thing I can suggest is that in the future you reach out to someone to test drive a vehicle if possible first before buying one, or at least ask about the way it drives first. If you hear it's a drift car, then it's best to avoid that vehicle unless that's what you're looking for.

No handling changes are set to change with this vehicle anytime soon besides the damage in the near future. Closing this issue.

**Closed by joevapes3** 2021-03-24 18:31 UTC
Labels: bug
