### ISSUE TITLE
[vehicles/electric] Big issues with the Tesla Roadster

### ISSUE THREAD

**Issue by roawrrr** [InZidiuZ/legacy-assets-issue-tracker#523] opened 2021-10-24 09:52 UTC
You would think a Tesla is electric but the Tesla roadster in city uses gas, which I believe is stupid especially when I was in a chase and it started leaking. Also it is a 4 seater but when in the back seats you can see the head very visibly sticking out of the roof, you can also see your feet under the car, another thing is that when inside of the car you are not able to see out of the vehicle if it tinted, if you hop out of the vehicle at even 3-5 miles an hour your body spins in a circle, another big issue is that it gets dirty insanely fast where I have to clean it every minute of driving  it out of all of these issues I believe it being electric but running on gas is the main problem.

My discord is Trexin#4551

This would make using the car more fun and realistic.

**Comment by Djmeowzle** [comment] 2021-11-15 12:12
Well, the car IRL is only a 2 seater, so if anything that would be the fix to the people heads sticking out, other than that, for balancing the car has to have its "charge" increased using fuel, otherwise, you'd have a car that could just drive forever. But i think some clipping adjustments could be made for feet sticking out, if the model allows it.

**Comment by DennisGHOSTDOGE** [comment] 2021-11-15 15:47
@Djmeowzle that part about the car being a 2 seater is entirely wrong. By looking at the car ingame you can see that it is clearly the new roadster, that has not yet been released. If you just took a second to look at the page of the roadster, you would have found this:
![image](https://user-images.githubusercontent.com/69167054/141810754-4cb073d2-2a5c-4075-80eb-f434f7dbb716.png)

Now to your second point. You say that a car that could drive forever would be op, although from what I heard, that already exists, being the standard gta electric and hybrid cars. I still couldn't test if that is true, since I don't have enough money on the main server to just go buying cars, and on the test server I somewhat can't get people to get me stuff, because of my time zone. 

Also, you don't even talk about his point about the gas leaking. A battery could get damaged, yes, which would mean a substantial lost of charge, yet the voltage would not keep dropping, so in my eyes, this doesn't make sense.

One more issue I saw when people used the car was the body clipping through the seat, just thought I'd mention that.

Not a hater or anything, just thought I'd mention everything wrong with this. I'd also love all the things above getting fixed, the sooner the better. Have a good one.

**Comment by DennisGHOSTDOGE** [comment] 2021-11-15 16:31
Certain it wasn't fixed
![image](https://user-images.githubusercontent.com/69167054/141818542-515f6f0c-322c-4ad5-bf31-2bca5e6b57ab.png)

**Comment by Nuziatella** [comment] 2021-11-17 12:46
This has been fixed.

**Comment by InZidiuZ** [comment] 2021-11-19 18:48
I tried reproducing the leaking of electric vehicles, but I have been completely unsuccessful. Is this still an issue?

**Comment by Nuziatella** [comment] 2021-12-09 19:42
This has been resolved with a script update.

**Closed by Nuziatella** 2021-12-09 19:42 UTC
